### 
POST http://127.0.0.1:3000/courier/add
Content-Type: application/json

{
    "name": "Коля"
}

###
GET http://127.0.0.1:3000/ping

### 
POST http://127.0.0.1:3000/courier/reserve
Content-Type: application/json

{
    "order_id": "abc",
    "courier_id": 1,
    "date": "25.12.2024 10:00"
}