@host=http://127.0.0.1:3000

### 
POST {{host}}/courier/add
Content-Type: application/json

{
    "name": "Коля"
}

### 
POST {{host}}/courier/add
Content-Type: application/json

{
    "name": "Петя"
}

### 
POST {{host}}/courier/add
Content-Type: application/json

{
    "name": "Вася"
}

### 
GET {{host}}/courier/add
Content-Type: application/json

{
    "courier_id": 4
}

### 
GET {{host}}/courier/reserve
Content-Type: application/json

{
    "order_id": "bbcdfe"
}

###
GET {{host}}/ping

### 
POST {{host}}/courier/reserve
Content-Type: application/json

{
    "order_id": "bbckdfe",
    "date": "25.12.2024 10:00"
}

###
DELETE {{host}}/courier/reserve
Content-Type: application/json

{
    "order_id": "abcd"
}